/*
 *
 */

package game.combat;

/**
 *
 * @author  Martin Pröhl alias MythGraphics
 * @version 1.0.0
 *
 */

import game.HasName;
import game.Resource;
import game.ResourceActionListener;
import static game.combat.DamageType.*;
import java.awt.Graphics;
import java.text.DecimalFormat;
import javax.swing.JPanel;

public class AttributePanel extends JPanel implements BattleActionListener, ResourceActionListener {

    public final static DecimalFormat FORMAT = new DecimalFormat("0.00");

    private final Combatant combatant;

    public AttributePanel(Combatant combatant) {
        this.combatant = combatant;
        if (combatant == null) {
            return;
        }
        initComponents();
//      combatant.addBattleActionListener(this);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldWeapon1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldWeapon2 = new javax.swing.JTextField();
        jTextFieldArmor1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldArmor2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDmg0 = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldBlock = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldKrit = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldLvl = new javax.swing.JTextField();
        jTextFieldDmg1 = new javax.swing.JTextField();
        jTextFieldDmg2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldDmg3 = new javax.swing.JTextField();
        jTextFieldDmg4 = new javax.swing.JTextField();
        jTextFieldDmg5 = new javax.swing.JTextField();
        jImgPanel = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if ( combatant.getImg() != null ) {
                    g.drawImage( combatant.getImg(), 0, 0, this );
                }
            }
        };
        jTextFieldAmmo1 = new javax.swing.JTextField();
        jTextFieldAmmo2 = new javax.swing.JTextField();
        jTextFieldDmg6 = new javax.swing.JTextField();
        jTextFieldDmg7 = new javax.swing.JTextField();
        jTextFieldDmg8 = new javax.swing.JTextField();
        jTextFieldDmg9 = new javax.swing.JTextField();
        jTextFieldDmg10 = new javax.swing.JTextField();
        jTextFieldDmg11 = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Kämpfer"));
        setFocusable(false);
        setOpaque(false);
        setRequestFocusEnabled(false);

        jTextField1.setEditable(false);
        jTextField1.setText(getAttributeValue(AttributeType.values()[0]));
        jTextField1.setToolTipText(AttributeType.values()[0].toString());
        jTextField1.setFocusable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Geschicklichkeit:");
        jLabel1.setFocusable(false);

        jTextField2.setEditable(false);
        jTextField2.setText(getAttributeValue(AttributeType.values()[1]));
        jTextField2.setToolTipText(AttributeType.values()[1].toString());
        jTextField2.setFocusable(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Intelligenz:");
        jLabel2.setFocusable(false);

        jTextField3.setEditable(false);
        jTextField3.setText(getAttributeValue(AttributeType.values()[2]));
        jTextField3.setToolTipText(AttributeType.values()[2].toString());
        jTextField3.setFocusable(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Stärke:");
        jLabel3.setFocusable(false);

        jLabel4.setText("Waffe 1:");
        jLabel4.setToolTipText("Haupthand");

        jLabel5.setText("Rüstung 1:");

        jTextFieldWeapon1.setEditable(false);
        jTextFieldWeapon1.setText(valueOf(combatant.getWeapon(0)));
        jTextFieldWeapon1.setToolTipText(getWeaponToolTip(combatant.getWeapon(0)));
        jTextFieldWeapon1.setFocusable(false);

        jLabel6.setText("Waffe 2:");
        jLabel6.setToolTipText("Nebenhand");

        jTextFieldWeapon2.setEditable(false);
        jTextFieldWeapon2.setText(valueOf(combatant.getWeapon(1)));
        jTextFieldWeapon2.setToolTipText(getWeaponToolTip(combatant.getWeapon(1)));
        jTextFieldWeapon2.setFocusable(false);

        jTextFieldArmor1.setEditable(false);
        jTextFieldArmor1.setText(getArmorString(combatant.getArmor(0)));
        jTextFieldArmor1.setToolTipText(getArmorTypeString(combatant.getArmor(0)));
        jTextFieldArmor1.setFocusable(false);

        jLabel7.setText("Rüstung 2:");

        jTextFieldArmor2.setEditable(false);
        jTextFieldArmor2.setText(getArmorString(combatant.getArmor(1)));
        jTextFieldArmor2.setToolTipText(getArmorTypeString(combatant.getArmor(1)));
        jTextFieldArmor2.setFocusable(false);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Schaden:");

        jTextFieldDmg0.setEditable(false);
        jTextFieldDmg0.setBackground(PHYSISCH.getColor());
        jTextFieldDmg0.setText(String.valueOf(combatant.getDamage(PHYSISCH)));
        jTextFieldDmg0.setToolTipText(PHYSISCH.name());
        jTextFieldDmg0.setFocusable(false);

        jLabelName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelName.setText(combatant.getName());
        jLabelName.setToolTipText(combatant.getType().toString());

        jLabel9.setText("Block:");

        jTextFieldBlock.setEditable(false);
        jTextFieldBlock.setText(FORMAT.format(combatant.getBlock())+"%");
        jTextFieldBlock.setToolTipText("Blockchance (%)");
        jTextFieldBlock.setFocusable(false);

        jLabel10.setText("Krit:");

        jTextFieldKrit.setEditable(false);
        jTextFieldKrit.setText(FORMAT.format(combatant.getCrit())+"%");
        jTextFieldKrit.setToolTipText("Kritische Trefferchance (%)");
        jTextFieldKrit.setFocusable(false);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Level:");

        jTextFieldLvl.setEditable(false);
        jTextFieldLvl.setText(String.valueOf(combatant.getLevel()));
        jTextFieldLvl.setToolTipText("Level");
        jTextFieldLvl.setFocusable(false);

        jTextFieldDmg1.setEditable(false);
        jTextFieldDmg1.setBackground(GIFT.getColor());
        jTextFieldDmg1.setText(String.valueOf(combatant.getDamage(GIFT)));
        jTextFieldDmg1.setToolTipText(GIFT.name());
        jTextFieldDmg1.setFocusable(false);

        jTextFieldDmg2.setEditable(false);
        jTextFieldDmg2.setBackground(FEUER.getColor());
        jTextFieldDmg2.setText(String.valueOf(combatant.getDamage(FEUER)));
        jTextFieldDmg2.setToolTipText(FEUER.name());
        jTextFieldDmg2.setFocusable(false);

        jLabel12.setText("Leben:");

        jProgressBar1.setForeground(new java.awt.Color(255, 102, 102));
        jProgressBar1.setMaximum(combatant.getHealth().getMax());
        jProgressBar1.setToolTipText(combatant.getHealth().getValue()+" / "+combatant.getHealth().getMax());
        jProgressBar1.setValue(combatant.getHealth().getValue());
        jProgressBar1.setStringPainted(true);

        jLabel13.setText("Rüstungswiderstand:");

        jTextFieldDmg3.setEditable(false);
        jTextFieldDmg3.setBackground(PHYSISCH.getColor());
        jTextFieldDmg3.setText(String.valueOf(combatant.getDamageReduction(PHYSISCH))+"%");
        jTextFieldDmg3.setToolTipText(PHYSISCH.name());
        jTextFieldDmg3.setFocusable(false);

        jTextFieldDmg4.setEditable(false);
        jTextFieldDmg4.setBackground(GIFT.getColor());
        jTextFieldDmg4.setText(String.valueOf(combatant.getDamageReduction(GIFT))+"%");
        jTextFieldDmg4.setToolTipText(GIFT.name());
        jTextFieldDmg4.setFocusable(false);

        jTextFieldDmg5.setEditable(false);
        jTextFieldDmg5.setBackground(FEUER.getColor());
        jTextFieldDmg5.setText(String.valueOf(combatant.getDamageReduction(FEUER))+"%");
        jTextFieldDmg5.setToolTipText(FEUER.name());
        jTextFieldDmg5.setFocusable(false);

        javax.swing.GroupLayout jImgPanelLayout = new javax.swing.GroupLayout(jImgPanel);
        jImgPanel.setLayout(jImgPanelLayout);
        jImgPanelLayout.setHorizontalGroup(
            jImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jImgPanelLayout.setVerticalGroup(
            jImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextFieldAmmo1.setEditable(false);
        jTextFieldAmmo1.setText(getAmmoString(combatant.getWeapon(0)));
        jTextFieldAmmo1.setToolTipText(getAmmoToolTip(combatant.getWeapon(0)));
        jTextFieldAmmo1.setFocusable(false);

        jTextFieldAmmo2.setEditable(false);
        jTextFieldAmmo2.setText(getAmmoString(combatant.getWeapon(1)));
        jTextFieldAmmo2.setToolTipText(getAmmoToolTip(combatant.getWeapon(1)));
        jTextFieldAmmo2.setFocusable(false);

        jTextFieldDmg6.setEditable(false);
        jTextFieldDmg6.setBackground(NUKLEAR.getColor());
        jTextFieldDmg6.setText(String.valueOf(combatant.getDamage(NUKLEAR)));
        jTextFieldDmg6.setToolTipText(NUKLEAR.name());
        jTextFieldDmg6.setFocusable(false);

        jTextFieldDmg7.setEditable(false);
        jTextFieldDmg7.setBackground(SÄURE.getColor());
        jTextFieldDmg7.setText(String.valueOf(combatant.getDamage(SÄURE)));
        jTextFieldDmg7.setToolTipText(SÄURE.name());
        jTextFieldDmg7.setFocusable(false);

        jTextFieldDmg8.setEditable(false);
        jTextFieldDmg8.setBackground(ELEKTRIZITÄT.getColor());
        jTextFieldDmg8.setText(String.valueOf(combatant.getDamage(ELEKTRIZITÄT)));
        jTextFieldDmg8.setToolTipText(ELEKTRIZITÄT.name());
        jTextFieldDmg8.setFocusable(false);

        jTextFieldDmg9.setEditable(false);
        jTextFieldDmg9.setBackground(NUKLEAR.getColor());
        jTextFieldDmg9.setText(String.valueOf(combatant.getDamageReduction(NUKLEAR))+"%");
        jTextFieldDmg9.setToolTipText(NUKLEAR.name());
        jTextFieldDmg9.setFocusable(false);

        jTextFieldDmg10.setEditable(false);
        jTextFieldDmg10.setBackground(SÄURE.getColor());
        jTextFieldDmg10.setText(String.valueOf(combatant.getDamageReduction(SÄURE))+"%");
        jTextFieldDmg10.setToolTipText(SÄURE.name());
        jTextFieldDmg10.setFocusable(false);

        jTextFieldDmg11.setEditable(false);
        jTextFieldDmg11.setBackground(ELEKTRIZITÄT.getColor());
        jTextFieldDmg11.setText(String.valueOf(combatant.getDamageReduction(ELEKTRIZITÄT))+"%");
        jTextFieldDmg11.setToolTipText(ELEKTRIZITÄT.name());
        jTextFieldDmg11.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldLvl, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldArmor1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldWeapon2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldArmor2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldKrit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldWeapon1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBlock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jImgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 2, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldDmg6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldDmg7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldDmg8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDmg0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDmg1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDmg2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldAmmo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldAmmo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldDmg9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldDmg11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jTextFieldDmg10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldDmg3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldDmg4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldDmg5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelName)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDmg0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDmg6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDmg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDmg8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDmg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDmg7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldDmg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldDmg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDmg11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldDmg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDmg10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldDmg9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldWeapon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAmmo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextFieldWeapon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6))
                                            .addComponent(jTextFieldAmmo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldArmor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldArmor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldKrit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jImgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void refresh() {
        jLabelName.setText( combatant.getName() );
        jLabelName.setToolTipText( combatant.getType().toString() );
        jProgressBar1.setMaximum( combatant.getHealth().getMax() );
        jProgressBar1.setToolTipText( combatant.getHealth().getValue() + " / " + combatant.getHealth().getMax() );
        jProgressBar1.setValue( combatant.getHealth().getValue() );
        jTextFieldLvl.setText( String.valueOf( combatant.getLevel() ));
        jTextFieldWeapon1.setText( valueOf( combatant.getWeapon( 0 )));
        jTextFieldWeapon1.setToolTipText( getWeaponToolTip( combatant.getWeapon( 0 )));
        jTextFieldWeapon2.setText( valueOf( combatant.getWeapon( 1 )));
        jTextFieldWeapon2.setToolTipText( getWeaponToolTip( combatant.getWeapon( 1 )));
        jTextFieldAmmo1.setText( getAmmoString( combatant.getWeapon( 0 )));
        jTextFieldAmmo1.setToolTipText( getAmmoToolTip( combatant.getWeapon( 0 )));
        jTextFieldAmmo2.setText( getAmmoString( combatant.getWeapon( 1 )));
        jTextFieldAmmo2.setToolTipText( getAmmoToolTip( combatant.getWeapon( 1 )));
        jTextFieldArmor1.setText( getArmorString( combatant.getArmor( 0 )));
        jTextFieldArmor1.setToolTipText( getArmorTypeString( combatant.getArmor( 0 )));
        jTextFieldArmor2.setText( getArmorString( combatant.getArmor( 1 )));
        jTextFieldArmor2.setToolTipText( getArmorTypeString( combatant.getArmor( 1 )));
        jTextFieldBlock.setText( FORMAT.format( combatant.getBlock() ) + "%" );
        jTextFieldKrit.setText(  FORMAT.format( combatant.getCrit()  ) + "%" );
        jTextFieldDmg0.setText( String.valueOf( combatant.getDamage( PHYSISCH )));
        jTextFieldDmg1.setText( String.valueOf( combatant.getDamage( GIFT )));
        jTextFieldDmg2.setText( String.valueOf( combatant.getDamage( FEUER )));
        jTextFieldDmg3.setText( String.valueOf( combatant.getDamageReduction( PHYSISCH )) + "%" );
        jTextFieldDmg4.setText( String.valueOf( combatant.getDamageReduction( GIFT )) + "%" );
        jTextFieldDmg5.setText( String.valueOf( combatant.getDamageReduction( FEUER )) + "%" );
    }

    @Override
    public void resourceActionPerformed(Resource r) {
        jProgressBar1.setMaximum( r.getMax() );
        jProgressBar1.setToolTipText( r.getValue() + " / " + r.getMax());
        jProgressBar1.setValue( r.getValue() );
    }

    @Override
    public void levelupPerformed(Combatant combatant) {
        jTextFieldLvl.setText( String.valueOf( combatant.getLevel() ));
        refresh();
    }

    @Override
    public void killPerformed(Combatant combatant) {
        jLabelName.setText( jLabelName.getText() + " (besiegt)" );
    }

    private String getAttributeValue(AttributeType aType) {
        if ( combatant instanceof Player player ) {
            return String.valueOf( player.getAttributeValue( aType ));
        }
        return "";
    }

    private static String valueOf(HasName obj) {
        if (obj == null) {
            return "";
        }
        return obj.getName();
    }

    private static String getArmorString(Blockable armor) {
        if ( armor == null ) {
            return "";
        }
        if ( armor instanceof Weapon) {
            return "";
        }
        return armor.getName();
    }

    private static String getAmmoString(AbstractWeapon w) {
        if ( w != null && w instanceof AmmoWeapon ) {
            Ammo ammo = ((AmmoWeapon) w).getAmmo();
            if (ammo == null) {
                return "";
            } else {
                return ammo.getStack() + "/" + ammo.getStackSize();
            }
        }
        return "";
    }

    private static String getAmmoToolTip(AbstractWeapon w) {
        if ( w != null && w instanceof AmmoWeapon ) {
            Ammo ammo = ((AmmoWeapon) w).getAmmo();
            if (ammo == null) {
                return null;
            } else {
                return ammo.getName() + " (" + ammo.getType() + ")";
            }
        }
        return null;
    }

    private static String getArmorTypeString(Blockable armor) {
        if ( armor != null && armor instanceof Armor a) {
            return "Typ: " + a.aType.toString();
        }
        return null;
    }

    private static String getWeaponToolTip(AbstractWeapon w) {
        if ( w == null ) {
            return "";
        }
        return "Klasse: " + w.wType.toString() + "\n" + w.getDescription();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jImgPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldAmmo1;
    private javax.swing.JTextField jTextFieldAmmo2;
    private javax.swing.JTextField jTextFieldArmor1;
    private javax.swing.JTextField jTextFieldArmor2;
    private javax.swing.JTextField jTextFieldBlock;
    private javax.swing.JTextField jTextFieldDmg0;
    private javax.swing.JTextField jTextFieldDmg1;
    private javax.swing.JTextField jTextFieldDmg10;
    private javax.swing.JTextField jTextFieldDmg11;
    private javax.swing.JTextField jTextFieldDmg2;
    private javax.swing.JTextField jTextFieldDmg3;
    private javax.swing.JTextField jTextFieldDmg4;
    private javax.swing.JTextField jTextFieldDmg5;
    private javax.swing.JTextField jTextFieldDmg6;
    private javax.swing.JTextField jTextFieldDmg7;
    private javax.swing.JTextField jTextFieldDmg8;
    private javax.swing.JTextField jTextFieldDmg9;
    private javax.swing.JTextField jTextFieldKrit;
    private javax.swing.JTextField jTextFieldLvl;
    private javax.swing.JTextField jTextFieldWeapon1;
    private javax.swing.JTextField jTextFieldWeapon2;
    // End of variables declaration//GEN-END:variables
}
