/*
 *
 */

package game.combat;

/**
 *
 * @author  Martin Pröhl alias MythGraphics
 * @version 1.0.0
 *
 */

import graphic.MultiTextRenderer;
import graphic.TextRenderer;
import java.awt.EventQueue;
import javax.swing.JDialog;
import javax.swing.JFrame;

public class CombatFrame extends JDialog implements CombatActionListener, BattleActionListener, DamageActionListener {

    private final Combatant player, enemy;
    private final AttributePanel jPanelTop, jPanelButtom;

    private boolean playerStrikesFirst = true;

    public CombatFrame(JFrame owner, Combatant player, Combatant enemy) {
        super(owner, "Fight!", true); // 'true' sorgt dafür, dass das Hauptfenster blockiert wird
        this.player     = player;
        this.enemy      = enemy;
        jPanelTop       = new AttributePanel(enemy);
        jPanelButtom    = new AttributePanel(player);
        initComponents();
        addActionListeners();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = jPanelTop;
        jPanel4 = jPanelButtom;
        jPanel3 = new javax.swing.JPanel();
        jTextPanel = new MultiTextRenderer();
        jButtonFight = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CombatFrame");
        setName("CombatFrame"); // NOI18N
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));
        jPanel1.add(jPanel2);
        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1);

        javax.swing.GroupLayout jTextPanelLayout = new javax.swing.GroupLayout(jTextPanel);
        jTextPanel.setLayout(jTextPanelLayout);
        jTextPanelLayout.setHorizontalGroup(
            jTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jTextPanelLayout.setVerticalGroup(
            jTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jButtonFight.setText("Fight!");
        jButtonFight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFightActionPerformed(evt);
            }
        });

        jButtonClose.setText("Schließen");
        jButtonClose.setEnabled(false);
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonFight, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClose, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
            .addComponent(jTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFight)
                    .addComponent(jButtonClose)))
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionListeners() {
        player.getHealth().addResourceActionListener(jPanelButtom);
        player.addBattleActionListener(jPanelButtom);
        player.addBattleActionListener(this);
        player.addCombatActionListener(this);
        enemy.getHealth().addResourceActionListener(jPanelTop);
        enemy.addBattleActionListener(jPanelTop);
        enemy.addBattleActionListener(this);
        enemy.addCombatActionListener(this);
    }

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        switch ( evt.getButton() ) {
            case 3 -> {
                // rechter Mausbutton
                dispose();
            }
            case 2 -> {
                // mittlerer Mausbutton
                setLocation( evt.getXOnScreen()-super.getWidth()/2, evt.getYOnScreen()-super.getHeight()/2 );
                repaint();
            }
            case 1 -> {
                // linker Mausbutton
                requestFocus();
            }
        }
    }//GEN-LAST:event_formMouseClicked

    private void toggleButtons(boolean fight_complete) {
        if (fight_complete) {
            jButtonFight.setEnabled(false);
            jButtonClose.setEnabled(true);
        } else {
            jButtonFight.setEnabled(true);
            jButtonClose.setEnabled(false);
        }
    }

    private void jButtonFightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFightActionPerformed
        if ( !player.isAlive() ) {
            show("Kampf abgeschlossen. " + player.getName() + " wurde besiegt.");
            toggleButtons(true);
            return;
        }
        if ( !enemy.isAlive() ) {
            if ( player instanceof Player p ) {
                p.addXP(Player.XP_PER_LEVEL);
            } else {
                player.setLevel( (byte) ( player.getLevel()+1 ));
            }
            show("Kampf abgeschlossen. " + enemy.getName() + " wurde besiegt.");
            toggleButtons(true);
            return;
        }
        // battle
        if (playerStrikesFirst) {
            battle(player, enemy);
            playerStrikesFirst = false;
        } else {
            battle(enemy, player);
            playerStrikesFirst = true;
        }
        show("----");
    }//GEN-LAST:event_jButtonFightActionPerformed

    private void show(String text) {
        ((TextRenderer) jTextPanel).showLine(text);
    }

    @Override
    public void dispose() {
        ((TextRenderer) jTextPanel).dispose();
        super.dispose();
    }

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    public void battle(Combatant attacker, Combatant defender) {
        show( attacker.getName() + " greift " + defender.getName() + " an:" );
        defender.takeDamage( attacker.makeDamage() );
    }

    @Override
    public void levelupPerformed(Combatant c) {
        show( "Level up! " + c.getName() + " ist stärker geworden: Level " + c.getLevel() );
    }

    @Override
    public void killPerformed(Combatant c) {
        show( "Tödlicher Schaden! " + c.getName() + " wurde umgehauen." );
    }

    @Override
    public void damagePerformed(Combatant c, int dmg) {
        if (dmg > 0) {
            show( c.getName() + " hat " + dmg + " Schaden erlitten.");
        } else {
            show( c.getName() + " hat keinen Schaden genommen." );
        }
    }

    @Override
    public void lethalDamagePerformed(Combatant c, int dmg, int overkillDmg) {
        show(
            c.getName() + " hat " +
            dmg + " Schaden erlitten, " +
            (dmg-overkillDmg) + " waren tödlich, " +
            overkillDmg + " überschüssig."
        );
    }

    @Override
    public void makeTotalDamagePerformed(Combatant c, int damage) {
        show( c.getName() + " teilt " + damage + " kumulierten Schaden aus." );
    }

    @Override
    public void takeDamagePerformed(Combatant c, Damage damage) {
        show( c.getName() + " nimmt " + damage + " Schaden." );
    }

    @Override
    public void makeDamagePerformed(Combatant c, Damage damage) {
        // show( c.getName() + " verursacht " + damage + " Schaden." );
    }

    @Override
    public void normalDamagePerformed(AbstractWeapon weapon, Damage damage) {
        show( weapon.getName() + ": " + damage.toString() + " Schaden." );
    }

    @Override
    public void kritDamagePerformed(AbstractWeapon weapon, Damage damage) {
        show( weapon.getName() + ": kritischer Treffer: " + damage + " Schaden." );
    }

    @Override
    public void deflectDamagePerformed(Blockable blockable, Damage damage) {
        show( "Angriff von " + blockable.getName() + " abgewehrt: " + damage + " Schaden verhindert." );
    }

    @Override
    public void changeStatsPerformed(AbstractWeapon weapon) {
        refreshUI();
    }

    private void refreshUI() {
        jPanelTop.refresh();
        jPanelButtom.refresh();
    }

    // for maintance
    public static void main(String args[]) {
        EventQueue.invokeLater( () -> {
            new CombatFrame(
                null, CombatFactory.getDefaultSpaceMarine(null), CombatFactory.getDefaultKriegerZerg()
            ).setVisible(true);
            System.exit(0);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonFight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jTextPanel;
    // End of variables declaration//GEN-END:variables

}
