/*
 *
 */

package game;

/**
 *
 * @author  Martin Pröhl alias MythGraphics
 * @version 1.0.0
 *
 */

import audio.AudioPlayer;
import static game.Resource.ResourceType.*;
import game.combat.Combatant;
import game.item.*;
import graphic.TextFrame;
import static graphic.io.BinaryIO.BINARYIO;
import graphic.io.ImageUtility;
import graphic.map.GameMap;
import graphic.map.MapType;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringTokenizer;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.plaf.basic.BasicProgressBarUI;
import util.ColorLibrary;
import util.EnumHelper;

public class GameFrame extends JFrame implements ItemEffectListener, ItemActionListener {

    public final static String CMD_ERROR1 = "Befehl nicht ausführbar. Argumente unzureichend.";

    public Color menuColor = new Color(255, 255, 255);

    static boolean loadCmdInput = false;
    static String playerName = "Teufelsmaus";

    private final TextFrame textFrame;
    private final Map<JLabel, ReUsable> iconMap;
    private final MouseAdapter iconMouseAdapter;

    private GameMap map;
    private GameRoutine routine;
    private BufferedImage playerImg;
    private Player player;
    private ConsoleInputController remote;
    private AudioPlayer audioPlayer;

    // MapType: land, space, uw
    public GameFrame(String[] tileMap, String mapType) {
        this.textFrame = new TextFrame(false);
        this.iconMap = new HashMap<>();
        this.iconMouseAdapter = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                iconLabelMouseClicked(evt);
            }
        };

        MapType mType = EnumHelper.getEnumFromStringAsOptional(MapType.class, mapType).orElseGet( () -> {
            System.err.println("Initialisieren der Map fehlgeschlagen - Typ unbekannt - Abbruch!");
            System.exit(255);
            return null;
        });
        this.map = mType.createMap(player);
        if (map == null) {
            System.err.println("Laden der Map fehlgeschlagen - Abbruch!");
            System.exit(255);
            return;
        }
        menuColor = ColorLibrary.invert( map.getAmbientColor() );

        if (loadCmdInput) {
            initRemote();
        }
        initPlayer();
        initComponents();
        initMoreComponents();
        initGame(mType);
        super.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Main.main(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        activateMap = new javax.swing.JMenuItem();
        deactivateMap = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        quit = new javax.swing.JMenuItem();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jGamePanel = map;
        jTopPanel = new javax.swing.JPanel();
        jProgressBarMana = new javax.swing.JProgressBar();
        jProgressBarHealth = new javax.swing.JProgressBar();
        jPlayerIconPanel = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (playerImg != null) {
                    g.drawImage( playerImg, 0, 0, this );
                }
            }
        };
        jIconPanel = new javax.swing.JPanel();
        jButtomPanel = new javax.swing.JPanel();
        creditField = new javax.swing.JTextField();
        jProgressBarRep = new javax.swing.JProgressBar();
        jRightPanel = new javax.swing.JPanel();
        jRightList = new javax.swing.JList<>();
        jLeftPanel = new javax.swing.JPanel();
        jLeftList = new javax.swing.JList<>();

        activateMap.setText("Map aktivieren");
        activateMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateMapActionPerformed(evt);
            }
        });
        jPopupMenu1.add(activateMap);

        deactivateMap.setText("Map deaktivieren");
        deactivateMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateMapActionPerformed(evt);
            }
        });
        jPopupMenu1.add(deactivateMap);
        jPopupMenu1.add(jSeparator1);

        quit.setText("Beenden");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        jPopupMenu1.add(quit);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GameFrame");
        setFocusCycleRoot(false);
        setLocation(new java.awt.Point(20, 20));
        setName("guiframe"); // NOI18N
        setUndecorated(true);
        setSize(new java.awt.Dimension(1500, 800));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLayeredPane1.setFocusable(false);

        jGamePanel.setFocusable(false);
        jGamePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGamePanelMouseClicked(evt);
            }
        });

        jTopPanel.setFocusable(false);
        jTopPanel.setOpaque(false);

        jProgressBarMana.setBackground(new Color(0,0,0,0));
        jProgressBarMana.setForeground(new java.awt.Color(51, 153, 255));
        jProgressBarMana.setToolTipText(player.getResource(MANA) != null ? player.getResource(MANA).toString() : "");
        jProgressBarMana.setValue(player.getResource(MANA) != null ? player.getResource(MANA).getValue() : 0);
        jProgressBarMana.setBorder(javax.swing.BorderFactory.createTitledBorder(null, jProgressBarMana.getToolTipText(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), menuColor)); // NOI18N
        jProgressBarMana.setFocusable(false);
        jProgressBarMana.setString(getProgressBarString(jProgressBarMana));
        jProgressBarMana.setStringPainted(true);

        jProgressBarHealth.setBackground(new Color(0,0,0,0));
        jProgressBarHealth.setForeground(new java.awt.Color(255, 102, 102));
        jProgressBarHealth.setToolTipText(player.getResource(HEALTH).toString());
        jProgressBarHealth.setValue(100);
        jProgressBarHealth.setBorder(javax.swing.BorderFactory.createTitledBorder(null, jProgressBarHealth.getToolTipText(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), menuColor)); // NOI18N
        jProgressBarHealth.setFocusable(false);
        jProgressBarHealth.setString(getProgressBarString(jProgressBarHealth));
        jProgressBarHealth.setStringPainted(true);

        jPlayerIconPanel.setFocusable(false);
        jPlayerIconPanel.setOpaque(false);

        javax.swing.GroupLayout jPlayerIconPanelLayout = new javax.swing.GroupLayout(jPlayerIconPanel);
        jPlayerIconPanel.setLayout(jPlayerIconPanelLayout);
        jPlayerIconPanelLayout.setHorizontalGroup(
            jPlayerIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPlayerIconPanelLayout.setVerticalGroup(
            jPlayerIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jIconPanel.setFocusable(false);
        jIconPanel.setOpaque(false);
        jIconPanel.setPreferredSize(new java.awt.Dimension(676, 100));
        jIconPanel.setLayout(new java.awt.GridLayout(3, 9));

        javax.swing.GroupLayout jTopPanelLayout = new javax.swing.GroupLayout(jTopPanel);
        jTopPanel.setLayout(jTopPanelLayout);
        jTopPanelLayout.setHorizontalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPlayerIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBarHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBarMana, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jIconPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTopPanelLayout.setVerticalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTopPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPlayerIconPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jTopPanelLayout.createSequentialGroup()
                        .addComponent(jProgressBarHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBarMana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jIconPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtomPanel.setFocusable(false);
        jButtomPanel.setOpaque(false);

        creditField.setEditable(false);
        creditField.setBackground(null);
        creditField.setForeground(menuColor);
        creditField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        creditField.setText(String.valueOf(player.getCredits()));
        creditField.setToolTipText(player.getResource(CREDIT).getName());
        creditField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, creditField.getToolTipText(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), menuColor)); // NOI18N
        creditField.setFocusable(false);
        creditField.setOpaque(false);

        jProgressBarRep.setBackground(new Color(0,0,0,0));
        jProgressBarRep.setForeground(new java.awt.Color(0, 153, 0));
        jProgressBarRep.setToolTipText(player.getResource(REPUTATION) != null ? player.getResource(REPUTATION).getName() : "");
        jProgressBarRep.setBorder(javax.swing.BorderFactory.createTitledBorder(null, jProgressBarRep.getToolTipText(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), menuColor)); // NOI18N
        jProgressBarRep.setFocusable(false);
        jProgressBarRep.setString(getProgressBarString(jProgressBarRep));
        jProgressBarRep.setStringPainted(true);

        javax.swing.GroupLayout jButtomPanelLayout = new javax.swing.GroupLayout(jButtomPanel);
        jButtomPanel.setLayout(jButtomPanelLayout);
        jButtomPanelLayout.setHorizontalGroup(
            jButtomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBarRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jButtomPanelLayout.setVerticalGroup(
            jButtomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jButtomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(creditField)
                    .addComponent(jProgressBarRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jRightPanel.setFocusable(false);
        jRightPanel.setOpaque(false);
        jRightPanel.setPreferredSize(new java.awt.Dimension(100, 421));

        jRightList.setBackground(new Color(255,255,255,80));
        jRightList.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Inventar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), menuColor)); // NOI18N
        jRightList.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRightList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jRightList.setToolTipText("Inventar");
        jRightList.setAutoscrolls(false);
        jRightList.setRequestFocusEnabled(false);
        jRightList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRightListMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jRightPanelLayout = new javax.swing.GroupLayout(jRightPanel);
        jRightPanel.setLayout(jRightPanelLayout);
        jRightPanelLayout.setHorizontalGroup(
            jRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRightList, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        jRightPanelLayout.setVerticalGroup(
            jRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRightList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLeftPanel.setFocusable(false);
        jLeftPanel.setOpaque(false);
        jLeftPanel.setPreferredSize(new java.awt.Dimension(100, 421));

        jLeftList.setBackground(new Color(255,255,255,80));
        jLeftList.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Diener", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), menuColor)); // NOI18N
        jLeftList.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLeftList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLeftList.setToolTipText("Diener");
        jLeftList.setAutoscrolls(false);
        jLeftList.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jLeftPanelLayout = new javax.swing.GroupLayout(jLeftPanel);
        jLeftPanel.setLayout(jLeftPanelLayout);
        jLeftPanelLayout.setHorizontalGroup(
            jLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLeftList, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLeftPanelLayout.setVerticalGroup(
            jLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLeftList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jGamePanelLayout = new javax.swing.GroupLayout(jGamePanel);
        jGamePanel.setLayout(jGamePanelLayout);
        jGamePanelLayout.setHorizontalGroup(
            jGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jGamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jGamePanelLayout.setVerticalGroup(
            jGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGamePanelLayout.createSequentialGroup()
                .addComponent(jTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.setLayer(jGamePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jGamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jGamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static BasicProgressBarUI getProgressBarUI(Color fTextColor, Color bTextColor) {
        return new BasicProgressBarUI() {
            @Override
            protected Color getSelectionBackground() {
                return bTextColor; // string color over background
            }
            @Override
            protected Color getSelectionForeground() {
                return fTextColor; // string color over foreground
            }
        };
    }

    public static BasicProgressBarUI getProgressBarUI() {
        return getProgressBarUI(Color.WHITE, Color.WHITE);
    }

    private void initMoreComponents() {
        jGamePanel.setBackground( map.getAmbientColor() );

        jProgressBarRep.setUI( getProgressBarUI() );
        jProgressBarHealth.setUI( getProgressBarUI() );
        jProgressBarMana.setUI( getProgressBarUI() );

        jLeftList.setVisible(false);
        jRightList.setVisible(false);
    }

    private void initPlayer() {
        player = new Player(playerName, textFrame);
        player.addResourceListener(this);
        player.addItemActionListener(this);
    }

    private void initGame(MapType mType) {
/*      ToDo: über MapRoutine laden
        BufferedImage playerImg = TilesetUtility.getSpriteSetHorizontal(
            IMAGEIO.loadImage(IMAGEIO.TILESET+"player/girl_red_swimsuit.png"), 140, 4
        )[0];
 */
        BufferedImage pImg = BINARYIO.loadImage(BINARYIO.SPRITE+"player/man1.png");
        player.setImg(pImg);
        this.playerImg = ImageUtility.scaleImage(
            pImg, jPlayerIconPanel.getWidth(), jPlayerIconPanel.getHeight()
        );
        jPlayerIconPanel.repaint(); // PlayerImg anzeigen

        if (remote == null) {
            // wenn Fernsteuerung nicht aktiv, GameRoutine laden
            switch (mType) {
                case SPACE  -> map.addCollisionActionListener( routine = new SpaceMapGameRoutine( player, this ));
                case LAND   -> map.addCollisionActionListener( routine = new LandMapGameRoutine(  player, this ));
                case UW     -> map.addCollisionActionListener( routine = new UWMapGameRoutine(    player, this ));
            }
        } else {
            routine = new PeacefulGameRoutine(player, null, this);
        }

        jLeftList.setModel( player.getMinionManager().getListModel() );
        jRightList.setModel( player.getInventory().getListModel() );
        jRightList.setCellRenderer( player.getInventory().getCellRenderer() );

        map.activate();
    }

    private void initRemote() {
        remote = new ConsoleInputController(this);

        remote.addCommand( "move", args -> {
            StringTokenizer tokenizer = new StringTokenizer(args, ", ", false);
            if ( tokenizer.countTokens() < 2 ) {
                System.err.println(CMD_ERROR1);
                return;
            }
            map.movePlayer( Integer.parseInt( tokenizer.nextToken() ), Integer.parseInt( tokenizer.nextToken() ));
        });
        remote.addCommand( "port", args -> {
            StringTokenizer tokenizer = new StringTokenizer(args, ", ", false);
            if ( tokenizer.countTokens() < 2 ) {
                System.err.println(CMD_ERROR1);
                return;
            }
            map.setPlayerPosition( Integer.parseInt( tokenizer.nextToken() ), Integer.parseInt( tokenizer.nextToken() ));
        });
        remote.addCommand( "textframe", args -> {
            StringTokenizer tokenizer = new StringTokenizer(args, " ", false);
            String[] params = new String[] { "", "", "" };
            for (int i = 0; (i < params.length) && tokenizer.hasMoreTokens(); ++i) {
                params[i] = tokenizer.nextToken();
            }
            textFrame.show( params[1], params[0], params[2] );
        });

        System.out.println("Remote-Steuerung bereit.");
    }

    public static String getProgressBarString(JProgressBar bar) {
        if ( bar.getToolTipText().isBlank() ) {
            bar.setVisible(false);
            return "";
        } else {
            bar.setVisible(true);
        }
        return (
            bar.getValue() + "/" + bar.getMaximum() + " | " +
            String.format( "%.1f", 100.0*bar.getValue()/bar.getMaximum() ) + " %"
        );
    }

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        dispose();
    }//GEN-LAST:event_quitActionPerformed

    private void activateMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateMapActionPerformed
        map.activate();
    }//GEN-LAST:event_activateMapActionPerformed

    private void deactivateMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateMapActionPerformed
        map.deactivate();
    }//GEN-LAST:event_deactivateMapActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        switch ( evt.getButton() ) {
            case 3 -> {
                // rechter Mausbutton
                jPopupMenu1.show( evt.getComponent(), evt.getX(), evt.getY() );
            }
            case 2 -> {
                // mittlerer Mausbutton
                setLocation( evt.getXOnScreen()-super.getWidth()/2, evt.getYOnScreen()-super.getHeight()/2 );
                repaint();
            }
            case 1 -> {
                // linker Mausbutton
                requestFocus();
            }
        }
    }//GEN-LAST:event_formMouseClicked

    private void iconLabelMouseClicked(MouseEvent evt) {
        JLabel jLabel = (JLabel) evt.getSource();
        if ( iconMap.get(jLabel) == null ) {
            return;
        }
        if ( evt.getButton() == MouseEvent.BUTTON3 ) {
            // rechter Mausbutton
            // Item ablegen, heißt: Effekt rückgängig machen und Item zurück ins Inventar legen
            jIconPanel.remove(jLabel); // Icon (JLabel) aus UI entfernen
            player.removeActiveItem( iconMap.remove( jLabel ));
        }
        if ( evt.getButton() == MouseEvent.BUTTON1 ) {
            // linker Mausbutton
            System.out.println( iconMap.get( jLabel ));
        }
    }

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        switch ( evt.getKeyCode() ) {
            case KeyEvent.VK_O  -> toggleVisibility(jLeftList);
            case KeyEvent.VK_I  -> toggleVisibility(jRightList);
            case KeyEvent.VK_M  -> toggleAudioPlayback();
            case KeyEvent.VK_1  -> playAudioTrack(0);
            case KeyEvent.VK_2  -> playAudioTrack(1);
            case KeyEvent.VK_3  -> playAudioTrack(2);
            case KeyEvent.VK_4  -> playAudioTrack(3);
            case KeyEvent.VK_5  -> playAudioTrack(4);
            case KeyEvent.VK_PLUS, KeyEvent.VK_ADD
                                -> audioPlayer.changeVolume(10);
            case KeyEvent.VK_MINUS, KeyEvent.VK_SUBTRACT
                                -> audioPlayer.changeVolume(-10);
            default             -> map.move(evt);
        }
    }//GEN-LAST:event_formKeyReleased

    private void playAudioTrack(int index) {
        List<String> audioTrackList = routine.getAudioTrackList();
        if ( audioTrackList == null || audioTrackList.isEmpty() ) {
            return;
        }
        if ( index >= audioTrackList.size() ) {
            System.out.println("Track-Nummer nicht definiert. Abspielen nicht möglich.");
            System.out.println(audioTrackList);
            return;
        }
        if (audioPlayer != null) {
            disposeAudioPlayer();
            try { Thread.sleep(100); } catch (InterruptedException e) {}
        }

        String audioFilePath = audioTrackList.get(index);
        try {
            audioPlayer = new AudioPlayer( BINARYIO.zip_path+BINARYIO.AUDIO+audioFilePath, true );
            new Thread(audioPlayer).start();
        } catch (UnsupportedAudioFileException | LineUnavailableException | IOException e) {
            System.err.println( "Fehler bei Audio-Wiedergabe: " + e.getMessage() );
        }
    }

    private void disposeAudioPlayer() {
        audioPlayer.dispose();
        audioPlayer = null;
    }

    private void toggleAudioPlayback() {
        if ( audioPlayer == null ) {
            return;
        }
        if ( audioPlayer.isPaused() ) {
            audioPlayer.resume();
        } else {
            audioPlayer.pause();
        }
    }

    private void toggleVisibility(JComponent component) {
        if ( component.isVisible() ) {
            component.setVisible(false);
        } else {
            component.setVisible(true);
        }
    }

    private void jGamePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGamePanelMouseClicked
        formMouseClicked(evt);
    }//GEN-LAST:event_jGamePanelMouseClicked

    private void jRightListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRightListMouseClicked
        if ( evt.getClickCount() >= 2 ) {
            // Doppelklick
            IsItem item = jRightList.getSelectedValue();
            boolean used = player.getInventory().use(item);
            if (!used) {
                System.out.println( item + " nicht verwendbar." );
            } else {
                System.out.println( item + " benutzt."); // debug
            }
        }
    }//GEN-LAST:event_jRightListMouseClicked

    @Override
    public void itemActionPerformed(IsItem item, ItemAction action, DialogOutputListener dialogListener) {
        switch (action) {
            case ItemAction.USE -> {
                if (item instanceof ReUsable reu) {
                    // Item im UI anzeigen
                    JLabel icon = new JLabel();
                    icon.setIcon( reu.getIcon() );
                    icon.addMouseListener(iconMouseAdapter);
                    iconMap.put(icon, reu);
                    jIconPanel.add(icon);
                } else {
                    // ToDo ggf. repaint des Player-UI erforderlich
                }
            }
            case ItemAction.REMOVE -> {
                System.out.println( item.getName() + " zurück ins Inventar gelegt.");
            }
        }
    }

    @Override
    public void itemEffectPerformed(Player p) {
        jProgressBarHealth.setMaximum( p.getHealth().getMax() );
        jProgressBarHealth.setValue( p.getHealth().getValue() );
        jProgressBarHealth.setString( getProgressBarString( jProgressBarHealth ));
        jProgressBarMana.setMaximum( p.getResource(MANA).getMax() );
        jProgressBarMana.setValue( p.getResource(MANA).getValue() );
        jProgressBarMana.setString( getProgressBarString( jProgressBarMana ));
        jProgressBarRep.setValue( p.getResource(REPUTATION).getValue() );
        creditField.setText( String.valueOf( p.getCredits() ));
    }

    @Override
    public void dispose() {
        if (audioPlayer != null) {
            disposeAudioPlayer();
        }
        System.out.println("GUI is closing ...");
        textFrame.dispose();
        map.dispose();
        super.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem activateMap;
    private javax.swing.JTextField creditField;
    private javax.swing.JMenuItem deactivateMap;
    private javax.swing.JPanel jButtomPanel;
    private javax.swing.JPanel jGamePanel;
    private javax.swing.JPanel jIconPanel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList<Combatant> jLeftList;
    private javax.swing.JPanel jLeftPanel;
    private javax.swing.JPanel jPlayerIconPanel;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JProgressBar jProgressBarHealth;
    private javax.swing.JProgressBar jProgressBarMana;
    private javax.swing.JProgressBar jProgressBarRep;
    private javax.swing.JList<IsItem> jRightList;
    private javax.swing.JPanel jRightPanel;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPanel jTopPanel;
    private javax.swing.JMenuItem quit;
    // End of variables declaration//GEN-END:variables

}
