/*
 *
 */

package graphic;

/**
 *
 * @author  Martin Pröhl alias MythGraphics
 * @version 1.0.0
 *
 */

import game.*;
import graphic.io.BinaryIO;
import static graphic.io.ImageUtility.scale;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Point;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class TextFrame extends JFrame implements DialogOutputListener {

    public final static Dimension DEFAULT_SIZE      = new Dimension(500, 200);
    public final static Dimension DEFAULT_IMG_SIZE  = new Dimension(200, 200);
    public final static Point DEFAULT_TEXT_POS      = new Point(200, 12);
    public final static Color DEFAULT_BG_COLOR      = new Color(242, 242, 242);

    final TextOverImageRenderer texter;

    private boolean standalone = false;
    private Dimension size = DEFAULT_SIZE;

    public static void main(String[] args) {
        if ( args == null || args.length == 0 ) {
            System.out.println("Argument 1: Text");
            System.out.println("Argument 2: Titel (optional)");
            System.out.println("Argument 3: Pfad-zu-Bild (optional)");
            return;
        }
        TextFrame texter = new TextFrame(true);
        if ( args.length == 1 ) {
            // nur Text
            texter.show("", args[0], "");
        }
        if ( args.length == 2 ) {
            // Text+Titel
            texter.show(args[1], args[0], "");
        }
        if ( args.length == 3 ) {
            // Text+Titel+Bild
            texter.show(args[1], args[0], args[2]);
        }
    }

    /**
     * Standalone full-size Text over Image frame.
     * @param size frame size
     */
    public TextFrame(Dimension size) {
        this(true, size, null, DEFAULT_TEXT_POS);
    }

    /**
     * Default constructor with default values.
     * @param standalone
     */
    public TextFrame(boolean standalone) {
        this(standalone, DEFAULT_SIZE, DEFAULT_IMG_SIZE, DEFAULT_TEXT_POS);
    }

    public TextFrame(boolean standalone, Dimension size, Dimension imgSize, Point textPos) {
        this.standalone = standalone;
        texter = new TextOverImageRenderer(textPos);
        texter.setImageSize(imgSize);
        texter.addActionListener( () -> {
            setNamePlate( texter.getCurrentMessage().getSource().getName() );
        });
        setSize(size);
        initComponents();
        setBackground(DEFAULT_BG_COLOR);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = texter;

        setTitle("TextFrame");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(20, 20));
        setName("textframe"); // NOI18N
        setUndecorated(true);
        setPreferredSize(size);
        setSize(size);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText(" ");

        jPanel1.setOpaque(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @see setLocation(Point p)
     * @param pos
     */
    public void setPosition(Point pos) {
        super.setLocation(pos);
    }

    @Override
    public final void setSize(int width, int height) {
        this.size = new Dimension(width, height);
        super.setSize(width, height);
        super.setPreferredSize(size);

        if (texter != null) {
            texter.setSize(width, height);
            texter.setPreferredSize( new Dimension( width, height )); // wichtig für den LayoutManager
        }

        // Neuberechnung des Layouts
        this.revalidate();
        this.repaint();
    }

    public TextOverImageRenderer getTexter() {
        return texter;
    }

    @Override
    public final void setBackground(Color color) {
        try {
            super.getContentPane().setBackground(color);
        } catch (NullPointerException e) {}
    }

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        if ( !texter.printNext() ) {
            super.setVisible(false);
        }
        if (standalone) {
            dispose();
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    public TextOverImageRenderer getRenderer() {
        return texter;
    }

    private void setNamePlate(String name) {
        jLabel1.setText( name + ":" );
    }

    public static HasUIImage loadUIImg(String imgpath) {
        if ( imgpath == null || imgpath.isBlank() ) {
            return new HasUIImage() {
                @Override
                public Image getImg() { return null; }
                @Override
                public ImageIcon getIcon() { return null; }
            };
        }

        Image img = scale(BinaryIO.BINARYIO.loadImage(imgpath), DEFAULT_IMG_SIZE.height );
        return new HasUIImage() {
            @Override
            public Image getImg() { return img; }
            @Override
            public ImageIcon getIcon() { return new ImageIcon(img); }
        };
    }

    @Override
    public void show(HasDialog dialog) {
        show( dialog.getDialog() );
    }

    private void show(LinkedList<Message> dialog) {
        if ( dialog == null || dialog.isEmpty() ) {
            return;
        }
        super.setVisible(true);
        while ( dialog.peek() != null ) {
            texter.show( dialog.poll() );
        }
    }

    // CLI usecase only
    public void show(String name, String message, String imgpath) {
        show( name, message, loadUIImg( imgpath ));
    }

    public void show(String name, String message, Image img) {
        show( new Message( message, new InteractiveObject( name, img )));
    }

    public void show(String name, String message, HasUIImage bg) {
        if ( bg == null ) {
            bg = loadUIImg(null);
        }
        show( new Message( message, new InteractiveObject( name, bg.getImg() )));
    }

    @Override
    public void show(Message msg) {
        if ( msg == null ) {
            return;
        }
        super.setVisible(true);
        texter.show(msg);
    }

    @Override
    public void dispose() {
        System.out.println("TextFrame is closing ...");
        texter.dispose();
        super.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
