# type: PROJECTILE, SPELL
# dmgtype: ELEKTRIZIT\u00c4T, GIFT, FEUER, NUKLEAR, PHYSISCH, S\u00c4URE
# size: Magazingr\u00f6\u00dfe
name=Magazin mit Plasmaladungen
description=Die Fire&Forget-Projektile, die aus jeder Standard-Waffe eine BFG machen! \
            Der nukleare Traum eines jeden Marines!
type=Projectile
size=25
dmgtype=NUKLEAR
dmg=50
img=
