# type: PROJECTILE, SPELL
# dmgtype: ELEKTRIZIT\u00c4T, GIFT, FEUER, NUKLEAR, PHYSISCH, S\u00c4URE
# size: Magazingr\u00f6\u00dfe
name=Magazin mit Hexafluorantimnons\u00e4urel\u00f6sung
description=Eine L\u00f6sung f\u00fcr absolut jedes Problem - echt \u00e4tzend!
type=Projectile
size=25
dmgtype=S\u00c4URE
dmg=75
img=
