# type: PROJECTILE, SPELL
# dmgtype: ELEKTRIZIT\u00c4T, GIFT, FEUER, NUKLEAR, PHYSISCH, S\u00c4URE
# size: Magazingr\u00f6\u00dfe
name=Plasmaladung
type=Projectile
size=25
dmgtype=NUKLEAR
dmg=50
img=
