# type: PROJECTILE, SPELL
# dmgtype: ELEKTRIZIT\u00c4T, GIFT, FEUER, NUKLEAR, PHYSISCH, S\u00c4URE
# size: Magazingr\u00f6\u00dfe
name=Magazin mit Ionenladungen
description=Der Tesla-Taser - Vorsicht Hochspannung!
type=Projectile
size=25
dmgtype=ELEKTRIZIT\u00c4T
dmg=40
img=
