name=M\u00fcnzbeutel
type=usable
img=sprites/player/coinbag.png
uiImg=
price=100
onFind=Ein Beutel mit M\u00fcnzen! Diese scheinen das lokale Zahlungsmittel zu sein. ... k\u00f6nnte sich als n\u00fctzlich erweisen!
onUse=Geld f\u00fcr mich!
