# 0-9f Text dieses Objektes (nach "onFind", optional)
# 0-9u Text dieses Objektes (nach "onUse", optional)
# 0-9fp Text des Player-Charakters (nach "onFind", optional)
# 0-9up Text des Player-Charakters (nach "onUse", optional)
# type: [leer], usable, reusable
name=Ring der Witwe
type=reusable
img=sprites/player/ring.png
uiImg=
price=100
onFind=Ohh, ein Ring! ... mit einer Inschrift ... in Latein:
onUse=Die Inschrift ist mir zwar zu aggro, aber h\u00fcbsch ist er trotzdem.
0f=Unus anulus,
1f=ut imperiam,
2f=omnes inveniam,
2fp=Das ist bestimmt ein Ehering ...
3f=in tenebras seducendum,
4f=et in perpetuum servitutem redigere.
5fp=... jep. Definitiv ein Ehering.
