# onFine0-9 Text dieses Objektes (nach "onFind", optional)
# onUse0-9  Text dieses Objektes (nach "onUse", optional)
# onFind0-9player Text des Player-Charakters (nach "onFind", optional)
# onUse0-9player Text des Player-Charakters (nach "onUse", optional)
# type: [leer], usable, reusable
name=Ring der Witwe
type=reusable
img=resources/sprites/player/ring.png
uiImg=
price=100
onUse=Die Inschrift ist mir zwar zu aggro, aber h\u00fcbsch ist er trotzdem.
onFind0=Ohh, ein Ring! ... mit einer Inschrift ... in Latein:
onFind1=Unus anulus,
onFind2=ut imperiam,
onFind3=omnes inveniam,
onFind4player=Das ist bestimmt ein Ehering ...
onFind5=in tenebras seducendum,
onFind6=et in perpetuum servitutem redigere.
onFind7player=... jep. Definitiv ein Ehering.
