# default: Hase, Katze, Ratte, KriegerZerg, FeuerZerg, GiftZerg, S\u00e4ureZerg, SchamanenZerg, NuklearZerg
# type: apotheker, chemiker, magier, krieger, schamane, soldat
# name
# type
# lvl
# img

default=GiftZerg
lvl=2

# name=Strahlende Ratte
# type=soldat
# lvl=2
# img=sprites/minion/rat.png
