# default: Hase, Katze, Ratte, KriegerZerg, FeuerZerg, GiftZerg
# type: apotheker, magier, krieger, space_marine
# name=
# type=
# lvl=
# img=

default=GiftZerg
lvl=1

# name=Strahlende Ratte
# type=space_marine
# lvl=1
# img=sprites/minion/rat.png
