quest_prolog=Seit gegr\u00fc\u00dft, wandernde Sch\u00f6nheit! Euresgleichen sieht man heutzutage selten im Freien.
quest_text=Nun zu Euch. Ich habe hier irgendwo meine Aufzeichnungen verloren. In diesem sind viele meiner Gedanken und Inspirationen festgehalten. Bitte findet es f\u00fcr mich, ihr werdet entlohnt.
quest_epilog=Ihr k\u00f6nnt einen Blick hinein werfen, wenn es Euch interessiert, erwartet aber nicht all zu viel Erkenntnis daraus.
quest_complete=Ihr habt es gefunden! Vielen Dank!
questobj_found=Was ist das?! Gebundenes Papier - wie pr\u00e4historisch! Das m\u00fcssen die gesuchten Aufzeichnungen sein - in einem Heft.
