# type: AXT, DOLCH, GEWEHR, KN\u00dcPPEL, KRIEGSCLEVE, SCHILD, SCHWERT, STAB, ZAUBER
# needAmmo: PROJECTILE, SPELL, NONE
name=Experimentelle Minigun
description=Klein aber fett! Der gl\u00e4nzendem Traum aus Stahl eines jeden SpaceMarines! \
            Dieses kleine Wunder moderner Ingenieurskunst feuert im Grunde Alles auf Jeden!
type=GEWEHR
needAmmo=PROJECTILE
img=

# dmg: Basis Waffenschaden (nur f\u00fcr munitionslose Waffen)
# dmgtype Schadenstyp (nur f\u00fcr munitionslose Waffen)
dmg=0
dmgtype=
